spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/overload?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: dls!@3528888

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: overload-registry-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: load-test

  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

upload:
  path: D:/workspace4_upload/test
